# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Python script from the host to the container
COPY requirements.txt .

# Install any dependencies required by the Python script
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# Specify the command to run your script
CMD ["coverage", "run", "-m", "pytest", "tests.py"]