services:
  # use the pre-build docker image from msft for sql_server_db container
  sql-server-db:
    container_name: sql-server-db
    build:
      context: tmp-sql/
      dockerfile: ../Dockerfile.sql
    ports:
      - "1433:1433"
    # volumes:
    #   - ../API_DB/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Mount the SQL script
    # environment:
    #   - MSSQL_SA_PASSWORD=MA1234@stuvi
    #   - ACCEPT_EULA=Y
    networks:
      - app-network
    # command: /bin/bash -c "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MA1234@stuvi -d master -i /docker-entrypoint-initdb.d/schema.sql"

  # build the Dockerfile.python container
  car-api:
    container_name: car-api
    image: car-api:v1.0
    build:
      context: tmp-app/
      dockerfile: ../Dockerfile.python
    depends_on:
      - sql-server-db
    ports:
    - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge