name: run pytest on pull request

on: 
  push:
    branches:
      - workflow-branch


jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependences
        run: |
            apt-get update
            apt-get install unixodbc unixodbc-dev --yes
            pip install -r requirements.txt

      - name: Run pytest
        run: pytest tests/tests.py


